In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
diabetes_df = pd.read_csv("Resources/merged.csv")
diabetes_df.head()

Unnamed: 0     SEQN  diabetes  insulin  worry_food  food_not_last  \
0           0  93705.0         2        2         3.0            3.0   
1           1  93711.0         2        2         3.0            3.0   
2           2  93712.0         2        2         2.0            2.0   
3           3  93713.0         2        2         3.0            3.0   
4           4  93714.0         1        1         3.0            3.0   

   balanced_meals  food_security  emergency_food  food_stamp  ...  \
0             3.0            1.0             2.0         2.0  ...   
1             3.0            1.0             2.0         2.0  ...   
2             2.0            3.0             2.0         1.0  ...   
3             3.0            1.0             2.0         2.0  ...   
4             3.0            1.0             1.0         2.0  ...   

   mod_work_activity  vig_work_activity  walk_bicycle  vig_rec_activity  \
0                  2                  2             2                 2   
1                  2                  2             1                 1   
2                  1                  1             2                 1   
3                  2                  2             1                 2   
4                  2                  2             2                 2   

   mod_rec_activity  height_in  10lb_losses  diet_health  week_meals_not_home  \
0                 1       63.0            4          3.0                  5.0   
1                 1       69.0            5          2.0                  4.0   
2                 1       68.0            5          4.0                 12.0   
3                 1       70.0            5          4.0                  0.0   
4                 2       60.0            4          4.0                  5.0   

   month_frozen_food  
0                0.0  
1                0.0  
2                0.0  
3                3.0  
4                8.0  

[5 rows x 30 columns]

In [2]:
diabetes_df.nunique()

Unnamed: 0               3441
SEQN                     3441
diabetes                    3
insulin                     2
worry_food                  3
food_not_last               3
balanced_meals              3
food_security               4
emergency_food              2
food_stamp                  2
monthly_income             12
family_savings              2
grocery_transport           9
health_insurance            2
pulse                       2
bmi                       383
weight                    916
12mo_alcohol               11
many_drinks_regularly       2
minutes_sedentary          41
mod_work_activity           2
vig_work_activity           2
walk_bicycle                2
vig_rec_activity            2
mod_rec_activity            2
height_in                  31
10lb_losses                 5
diet_health                 5
week_meals_not_home        22
month_frozen_food          30
dtype: int64

In [3]:
# Drop the option 3 in the diabetes row

diabetes_df.drop(diabetes_df.index[diabetes_df['diabetes'] == 3], inplace=True)
diabetes_df.head()

Unnamed: 0     SEQN  diabetes  insulin  worry_food  food_not_last  \
0           0  93705.0         2        2         3.0            3.0   
1           1  93711.0         2        2         3.0            3.0   
2           2  93712.0         2        2         2.0            2.0   
3           3  93713.0         2        2         3.0            3.0   
4           4  93714.0         1        1         3.0            3.0   

   balanced_meals  food_security  emergency_food  food_stamp  ...  \
0             3.0            1.0             2.0         2.0  ...   
1             3.0            1.0             2.0         2.0  ...   
2             2.0            3.0             2.0         1.0  ...   
3             3.0            1.0             2.0         2.0  ...   
4             3.0            1.0             1.0         2.0  ...   

   mod_work_activity  vig_work_activity  walk_bicycle  vig_rec_activity  \
0                  2                  2             2                 2   
1                  2                  2             1                 1   
2                  1                  1             2                 1   
3                  2                  2             1                 2   
4                  2                  2             2                 2   

   mod_rec_activity  height_in  10lb_losses  diet_health  week_meals_not_home  \
0                 1       63.0            4          3.0                  5.0   
1                 1       69.0            5          2.0                  4.0   
2                 1       68.0            5          4.0                 12.0   
3                 1       70.0            5          4.0                  0.0   
4                 2       60.0            4          4.0                  5.0   

   month_frozen_food  
0                0.0  
1                0.0  
2                0.0  
3                3.0  
4                8.0  

[5 rows x 30 columns]

In [4]:
diabetes_df = diabetes_df.drop(columns = ['Unnamed: 0', 'SEQN'])
diabetes_df

diabetes  insulin  worry_food  food_not_last  balanced_meals  \
0            2        2         3.0            3.0             3.0   
1            2        2         3.0            3.0             3.0   
2            2        2         2.0            2.0             2.0   
3            2        2         3.0            3.0             3.0   
4            1        1         3.0            3.0             3.0   
...        ...      ...         ...            ...             ...   
3436         2        2         3.0            3.0             3.0   
3437         2        2         3.0            3.0             3.0   
3438         2        2         2.0            2.0             2.0   
3439         2        2         3.0            3.0             3.0   
3440         2        2         2.0            2.0             2.0   

      food_security  emergency_food  food_stamp  monthly_income  \
0               1.0             2.0         2.0             2.0   
1               1.0             2.0         2.0            12.0   
2               3.0             2.0         1.0             4.0   
3               1.0             2.0         2.0             7.0   
4               1.0             1.0         2.0             6.0   
...             ...             ...         ...             ...   
3436            1.0             2.0         2.0             3.0   
3437            1.0             2.0         1.0            12.0   
3438            3.0             2.0         2.0            10.0   
3439            1.0             2.0         2.0             7.0   
3440            4.0             2.0         2.0             7.0   

      family_savings  ...  mod_work_activity  vig_work_activity  walk_bicycle  \
0                2.0  ...                  2                  2             2   
1                1.0  ...                  2                  2             1   
2                2.0  ...                  1                  1             2   
3                2.0  ...                  2                  2             1   
4                2.0  ...                  2                  2             2   
...              ...  ...                ...                ...           ...   
3436             1.0  ...                  2                  1             1   
3437             1.0  ...                  1                  1             2   
3438             1.0  ...                  1                  2             2   
3439             2.0  ...                  2                  2             2   
3440             2.0  ...                  2                  2             2   

      vig_rec_activity  mod_rec_activity  height_in  10lb_losses  diet_health  \
0                    2                 1       63.0            4          3.0   
1                    1                 1       69.0            5          2.0   
2                    1                 1       68.0            5          4.0   
3                    2                 1       70.0            5          4.0   
4                    2                 2       60.0            4          4.0   
...                ...               ...        ...          ...          ...   
3436                 1                 1       63.0            1          3.0   
3437                 2                 2       72.0            5          5.0   
3438                 2                 2       65.0            1          2.0   
3439                 2                 1       69.0            1          2.0   
3440                 2                 2       69.0            1          4.0   

      week_meals_not_home  month_frozen_food  
0                     5.0                0.0  
1                     4.0                0.0  
2                    12.0                0.0  
3                     0.0                3.0  
4                     5.0                8.0  
...                   ...                ...  
3436                  3.0                2.0  
3437                  6.0             

In [5]:
dummies_diabetes_df = pd.get_dummies(diabetes_df, dtype=float)
dummies_diabetes_df

diabetes  insulin  worry_food  food_not_last  balanced_meals  \
0            2        2         3.0            3.0             3.0   
1            2        2         3.0            3.0             3.0   
2            2        2         2.0            2.0             2.0   
3            2        2         3.0            3.0             3.0   
4            1        1         3.0            3.0             3.0   
...        ...      ...         ...            ...             ...   
3436         2        2         3.0            3.0             3.0   
3437         2        2         3.0            3.0             3.0   
3438         2        2         2.0            2.0             2.0   
3439         2        2         3.0            3.0             3.0   
3440         2        2         2.0            2.0             2.0   

      food_security  emergency_food  food_stamp  monthly_income  \
0               1.0             2.0         2.0             2.0   
1               1.0             2.0         2.0            12.0   
2               3.0             2.0         1.0             4.0   
3               1.0             2.0         2.0             7.0   
4               1.0             1.0         2.0             6.0   
...             ...             ...         ...             ...   
3436            1.0             2.0         2.0             3.0   
3437            1.0             2.0         1.0            12.0   
3438            3.0             2.0         2.0            10.0   
3439            1.0             2.0         2.0             7.0   
3440            4.0             2.0         2.0             7.0   

      family_savings  ...  mod_work_activity  vig_work_activity  walk_bicycle  \
0                2.0  ...                  2                  2             2   
1                1.0  ...                  2                  2             1   
2                2.0  ...                  1                  1             2   
3                2.0  ...                  2                  2             1   
4                2.0  ...                  2                  2             2   
...              ...  ...                ...                ...           ...   
3436             1.0  ...                  2                  1             1   
3437             1.0  ...                  1                  1             2   
3438             1.0  ...                  1                  2             2   
3439             2.0  ...                  2                  2             2   
3440             2.0  ...                  2                  2             2   

      vig_rec_activity  mod_rec_activity  height_in  10lb_losses  diet_health  \
0                    2                 1       63.0            4          3.0   
1                    1                 1       69.0            5          2.0   
2                    1                 1       68.0            5          4.0   
3                    2                 1       70.0            5          4.0   
4                    2                 2       60.0            4          4.0   
...                ...               ...        ...          ...          ...   
3436                 1                 1       63.0            1          3.0   
3437                 2                 2       72.0            5          5.0   
3438                 2                 2       65.0            1          2.0   
3439                 2                 1       69.0            1          2.0   
3440                 2                 2       69.0            1          4.0   

      week_meals_not_home  month_frozen_food  
0                     5.0                0.0  
1                     4.0                0.0  
2                    12.0                0.0  
3                     0.0                3.0  
4                     5.0                8.0  
...                   ...                ...  
3436                  3.0                2.0  
3437                  6.0             

In [6]:
y = dummies_diabetes_df["diabetes"].values
X = dummies_diabetes_df.drop(["diabetes"], axis=1).values
print(X)
print(y)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=50)

[[ 2.  3.  3. ...  3.  5.  0.]
 [ 2.  3.  3. ...  2.  4.  0.]
 [ 2.  2.  2. ...  4. 12.  0.]
 ...
 [ 2.  2.  2. ...  2.  1.  1.]
 [ 2.  3.  3. ...  2.  1.  0.]
 [ 2.  2.  2. ...  4.  2.  0.]]
[2 2 2 ... 2 2 2]


In [7]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [8]:
# Changed the number of hidden nodes

number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  10
hidden_nodes_layer2 = 20

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=3, activation="softmax"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                280       
_________________________________________________________________
dense_1 (Dense)              (None, 20)                220       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 63        
Total params: 563
Trainable params: 563
Non-trainable params: 0
_________________________________________________________________


In [9]:
nn.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [10]:
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
79/79 [==============================] - 1s 5ms/step - loss: 0.8259 - accuracy: 0.6705
Epoch 2/100
79/79 [==============================] - 0s 4ms/step - loss: 0.5479 - accuracy: 0.8411
Epoch 3/100
79/79 [==============================] - 0s 4ms/step - loss: 0.4661 - accuracy: 0.8450
Epoch 4/100
79/79 [==============================] - 0s 4ms/step - loss: 0.4222 - accuracy: 0.8510: 0s - loss: 0.4583 - accura
Epoch 5/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3871 - accuracy: 0.8658
Epoch 6/100
79/79 [==============================] - 0s 4ms/step - loss: 0.3634 - accuracy: 0.8798
Epoch 7/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3499 - accuracy: 0.8810
Epoch 8/100
79/79 [==============================] - 0s 6ms/step - loss: 0.3417 - accuracy: 0.8818
Epoch 9/100
79/79 [==============================] - 0s 6ms/step - loss: 0.3357 - accuracy: 0.8822
Epoch 10/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3322 

In [11]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

27/27 - 1s - loss: 0.3996 - accuracy: 0.8719
Loss: 0.39960578083992004, Accuracy: 0.8718562722206116
